services:
  next-js-app:
    build:
      context: ./next-js-app
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - internal


  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - next-js-app
    networks:
      - internal
      - external
    #UPDATE
  ragchat:
    image: rag-chatbot
    networks:
      - internal
      - external
    command: streamlit run src/app.py --server.port=8502 --server.address=0.0.0.0 --server.baseUrlPath=/chat
    ports:
      - "8502:8502"


networks:
  internal:
    internal: true
  external:
    external: false

