services:
  # Next.js Application
  next-js-app:
    build:
      context: ./next-js-app
      dockerfile: Dockerfile
    depends_on:
      - ragchat
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    build: ./nginx
    depends_on:
      - next-js-app
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    restart: unless-stopped

  # RAG Chatbot
  ragchat:
    image: rag-chatbot
    command: streamlit run src/app.py --server.port=8502 --server.address=0.0.0.0 --server.baseUrlPath=/chat
    ports:
      - "8502:8502"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
