version: '3.8'
services:
  next-js-app:
    build:
      context: ./next-js-app
      dockerfile: Dockerfile
    depends_on:
      - ragchat
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "3000:3000"
      - "80:3000"
    restart: unless-stopped

#  nginx:
#    build: ./nginx
#    depends_on:
#      - next-js-app
#    ports:
#      - "443:443"
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt
#    networks:
#      - app-network
#    restart: unless-stopped

  ragchat:
    image: rag-chatbot
    command: streamlit run src/app.py --server.port=8502 --server.address=0.0.0.0 --server.baseUrlPath=/chat
    ports:
      - "8502:8502"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
